import React, { useState, useEffect } from 'react';
import TrackList from '../TrackList/TrackList';
import './Playlist.css';
import Spotify from '../spotify/spotify';

function Playlist({ playlistName, tracks, onRemove, onRename, onSave, onViewPlaylist }) {
  const [isEditing, setIsEditing] = useState(false);
  const [newName, setNewName] = useState(playlistName);
  const [userInfo, setUserInfo] = useState(null); // Store user info

  useEffect(() => {
    // Fetch user info from Spotify API if logged in
    const fetchUserInfo = async () => {
      const accessToken = Spotify.getAccessToken();
      if (accessToken) {
        try {
          const response = await Spotify.getUserInfo(accessToken);
          setUserInfo(response); // Save user info
        } catch (error) {
          console.error('Error fetching user info:', error);
        }
      }
    };

    fetchUserInfo();
  }, []);

  const handleChange = (event) => {
    setNewName(event.target.value);
  };

  const handleBlur = () => {
    if (newName !== playlistName) {
      onRename(newName);
    }
    setIsEditing(false);
  };

  const handleKeyPress = (event) => {
    if (event.key === 'Enter') {
      handleBlur();
    }
  };

  const removeTrack = (trackId) => {
    const updatedPlaylist = tracks.filter((track) => track.id !== trackId);
    onRemove(updatedPlaylist);
  };

  const savePlaylist = () => {
    if (!tracks.length) {
      alert('Your playlist is empty!');
      return;
    }

    const trackUris = tracks.map((track) => track.uri);

    // Integrate Spotify API logic
    const accessToken = Spotify.getAccessToken();
    if (!accessToken) {
      alert('Unable to save playlist. Please log in to Spotify.');
      return;
    }

    const endpoint = 'https://api.spotify.com/v1/me/playlists';
    const headers = { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' };

    // Create a new playlist
    fetch(endpoint, {
      method: 'POST',
      headers: headers,
      body: JSON.stringify({
        name: newName,
        description: 'Generated by Jammming',
        public: true,
      }),
    })
      .then((response) => response.json())
      .then((playlist) => {
        const playlistId = playlist.id;
        const addTracksEndpoint = `https://api.spotify.com/v1/playlists/${playlistId}/tracks`;
        return fetch(addTracksEndpoint, {
          method: 'POST',
          headers: headers,
          body: JSON.stringify({ uris: trackUris }),
        });
      })
      .then((response) => {
        if (response.ok) {
          alert(`Playlist "${newName}" saved successfully!`);
          onRemove([]); // Clear the playlist
        } else {
          throw new Error('Failed to add tracks to playlist');
        }
      })
      .catch((error) => {
        console.error('Error saving playlist:', error);
        alert('An error occurred while saving the playlist. Please try again.');
      });
  };

  return (
    <div className="Playlist">
      {/* User info display */}
      {userInfo && (
        <div className="user-info">
          <p>Logged in as: {userInfo.display_name}</p>
          <img src={userInfo.images[0]?.url} alt="Profile" width="50" />
        </div>
      )}

      <h2>
        {isEditing ? (
          <input
            type="text"
            value={newName}
            onChange={handleChange}
            onBlur={handleBlur}
            onKeyDown={handleKeyPress}
            autoFocus
          />
        ) : (
          <span onClick={() => setIsEditing(true)}>{playlistName}</span>
        )}
      </h2>

      <TrackList tracks={tracks} onRemove={removeTrack} />

      {/* Add to Playlist / Save to Playlist Button */}
      <button className="SaveButton"
       onClick={savePlaylist}
       disabled={isSaving}
       >
        Save to Playlist
      </button>

      {/* View Playlist button to redirect */}
      <button className="ViewPlaylistButton" onClick={onViewPlaylist}>
        View Playlist
      </button>
    </div>
  );
}

export default Playlist;
